### ISSUE TITLE
Initial search UI based on NWBib

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources-web#1]
Create initial search UI for lobid-resources based on NWBib.

Original issue: https://github.com/hbz/lobid-resources/issues/136

**Comment by fsteeg** [comment]
Deployed to http://alpha.lobid.org/resources

`beta.lobid.org/resources` and `test.lobid.org/resources` are used by the index routes and integrated in Edoweb, NWBib etc, so we can't just replace them, but we'll have to do a coordinated switch. I'll open an issue for that.

@acka47 As this is the initial trimmed-down NWBib, I don't think we should review this in detail here. I worked in master and won't open a pull request. I'll open issues for the next steps, and you could do the same for things you notice.

**Comment by acka47** [comment]
> @acka47 As this is the initial trimmed-down NWBib, I don't think we should review this in detail here. I worked in master and won't open a pull request. I'll open issues for the next steps, and you could do the same for things you notice.

Then I will close this issue.
