### ISSUE TITLE
Automate context updates

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources-web#13]
Currently, the context is generated from labels.json in lobid-rdf-to-json. When changed, it has to be manually copied to lobid-resources-web, from where it's serverd with CORS header and proper content type. We should automate this. Some ideas:

- Merge lobid-resources, lobid-rdf-to-json, and lobid-resources-web
- Add dependency to lobid-rdf-to-json in lobid-resources-web and generate context

**Comment by dr0i** [comment]
As indeed lobid-resources, lobid-rdf-to-json, and lobid-resources-web are merged this issue is resolved.
Closing.
