### ISSUE TITLE
DE-605 missing in owner facet

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources-web#15]
We can search for resources owned by DE-605:
http://alpha.lobid.org/resources/search?q=*&from=135&owner=http%3A%2F%2Flobid.org%2Forganisation%2FDE-605

But it does not show up in the owner facet.

**Comment by jschnasse** [comment]
Concerning the view of a single item:
The aleph/opac entry shows the room number in field "Notiz". This important information is missing in lobid. Also the link under signature (under "Details zum Bestand als Liste anzeigen") is broken.

**Comment by fsteeg** [comment]
Hm, the problem seems to come up only in specific situations.

For instance here it works:
http://alpha.lobid.org/resources/search?q=NRW&owner=http%3A%2F%2Flobid.org%2Forganisation%2FDE-605

But here it does not:
http://alpha.lobid.org/resources/search?q=digital&owner=http%3A%2F%2Flobid.org%2Forganisation%2FDE-605

**Comment by fsteeg** [comment]
Facets, like search, are still based on API 1.x. I think it makes sense to work on this after https://github.com/hbz/lobid-resources-web/issues/8.

> The aleph/opac entry shows the room number in field "Notiz".

For the "Notiz", I've openend https://github.com/hbz/lobid-resources/issues/167

> Also the link under signature (under "Details zum Bestand als Liste anzeigen") is broken.

The links will work when we switch the domain, see https://github.com/hbz/lobid-resources-web/issues/6.

**Comment by fsteeg** [comment]
Fixed with currently staged fix for https://github.com/hbz/lobid-resources/issues/340:

http://stage.lobid.org/resources/search?owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-605

**Comment by ChristophEwertowski** [comment]
+1

**Comment by fsteeg** [comment]
Problem still/again present in production, reopening. See:
http://lobid.org/resources/search?owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-605

It looks good on staging however:
http://stage.lobid.org/resources/search?owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-605

**Comment by fsteeg** [comment]
Now both work, weird. Closing.
