### ISSUE TITLE
Fix "issued" field for non-NWBib titles

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources-web#18]
See:

http://alpha.lobid.org/resources/search?q=k%C3%B6ln
http://alpha.lobid.org/resources/search?q=k%C3%B6ln&set=NWBib

Is our normalization tailored to the NWBib values? Is the cataloging practice different for NWBib?

**Comment by acka47** [comment]
> Is our normalization tailored to the NWBib values? Is the cataloging practice different for NWBib?

Yes and yes. (There must be a date field that isn't normalized by us and that is not used within NWBib cataloging.) This obviously is field 089, ind2=1, see e.g. HT000398485 ([source](http://lobid.org/hbz01/HT000398485), [JSON-LD](http://lobid.org/resources/HT000398485)):

```xml
<datafield tag="089" ind1="-" ind2="1">
<subfield code="a">1981 = Vollst. überarb. Aufl. 6</subfield>
</datafield>
```

Usually, this field deals with volume information. From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mabTitelBibliographischeDaten2001.txt?__blob=publicationFile):

```
089       BANDANGABEN IN VORLAGEFORM

          Indikator:
          blank = nicht definiert
```

A look at the morph reveals that this field indeed is not normalized, see [current morph, lines 675-684](https://github.com/hbz/lobid-resources/blob/7523c206b124e8ae9370fe1e88ea80fa42ecb13a/src/main/resources/morph-hbz01-to-lobid.xml#L675-L684)

I noticed that for some resources, though the publication date is not normalized it is shown correctly in the result list anyway, e.g. http://lobid.org/resources/HT003104331, look at the list at http://alpha.lobid.org/resources/search?q=+Biblioth%C3%A8que+universelle+des+romans

**Comment by acka47** [comment]
We currently only normalize publication dates from `619[ab][-1].a`, see [current morph, lines 708-710](https://github.com/hbz/lobid-resources/blob/7523c206b124e8ae9370fe1e88ea80fa42ecb13a/src/main/resources/morph-hbz01-to-lobid.xml#L708-L710). We will have to also do this for `089` or maybe even all the fields in [current morph, lines 675-684](https://github.com/hbz/lobid-resources/blob/7523c206b124e8ae9370fe1e88ea80fa42ecb13a/src/main/resources/morph-hbz01-to-lobid.xml#L675-L684).

**Comment by fsteeg** [comment]
Note that current search in http://alpha.lobid.org/resources/ still uses API 1.x, so what we see there is not what we have in the 2.0 index.
