### ISSUE TITLE
Wrong "Publikationstyp"  value for journals

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources-web#20]
Currently, all journals have as "Publikationstyp" "Publication", see any resource from http://alpha.lobid.org/resources/search?q=*&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FJournal. Obviously, the type is taken from the publication object instead from the root "type" statement on root level. 

E.g. the JSON-LD for http://alpha.lobid.org/resources/HT018314858 contains:

```json
{
   "publication":[
      {
         "endDate":"2014",
         "location":"Brasted, Kent",
         "publishedBy":"Russell",
         "startDate":"2014",
         "type":[
            "Publication"
         ]
      }
   ],
   "type":[
      "BibliographicResource",
      "Journal"
   ]
}
```

**Comment by fsteeg** [comment]
Same issue in NWBib, see: http://nwbib.de/HT018485120
