### ISSUE TITLE
Don't show all works after selection of subject and then search for term

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources-web#36]
If I search for a term in the simple search mask, filter by using a subject facet and then search again, I get all results of the catalog instead of results for the second searched string. 
Example: First search for "Sonne" (13458 hits), choose subject facet "Predigt" and search for "dunkel" (19755044 hits, normally 2485). 
The same counts for using of the publication year bar.

**Comment by fsteeg** [comment]
Discussed this with @acka47 and we're not sure if this actually makes sense. Currently the conceptual workflow is: 1) search 2) restrict search result with facets. A new search is a new search that can be restricted again. On the other hand, if we modify the search (e.g. restrict with `-term`) after faceting, it would be nice to keep the facets. @acka47 suggested to look at other systems.

**Comment by ChristophEwertowski** [comment]
Yes, my intuition was also that a new search should be a new search. To explicate the above example a bit further:
1. Search for term "Sonne" -> show all hits for search term OK
2. Choose subject facet "Predigt" -> limit results and show them OK
3. Search for term "dunkel" -> delete subject facet OK | show me all resources regardless of new search term NOT OK 

But I agree that looking at other systems is a good idea.

**Comment by ChristophEwertowski** [comment]
A few quick glances above some combined faceting and search: 
* Amazon.de shows numbers of facets or sub categories after searching and choosing of a main category. If searching for a new term it stays in the main category (for example it stays in the video section).
* Ebay also stays in the selected categories.
* [Worldcat](worldcat.org) leaves the previous selected facet after searching for a new term.
* Likewise for the catalog of the [North Carolina State University](http://www.lib.ncsu.edu/catalog/).
* The [catalog of the DNB](https://portal.dnb.de/opac.htm?method=showSearchForm#top)

**Comment by ChristophEwertowski** [comment]
Ticket identical with https://github.com/hbz/lobid-resources/issues/222 and resolved in https://github.com/hbz/lobid-resources/pull/223. Because of that I close this ticket.

**Comment by acka47** [comment]
http://katalogbeta.slub-dresden.de/ resets the facets when searching with a new term. Primo (at least in Mannheim) also resets the facets.
