### ISSUE TITLE
Institutions shouldn't be called "Autor/in"

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources-web#37]
For example the [Jahresbericht of the Ifo-Institut für Wirtschaftsforschung](http://lobid.org/resources/HT005076504). Institutions are [issuing bodies](http://id.loc.gov/vocabulary/relators/isb.html) or [editors](http://id.loc.gov/vocabulary/relators/edt.html). I don't know if it's necessary to change the data but at least call it "Herausgeber" at the frontend. What do you mean @acka47 ?
(Posting this issue in this repo because unsure if data change is necessary.)

**Comment by fsteeg** [comment]
Just as some further information: this is a data level issue, see `role` in:
http://lobid.org/resources/HT005076504?format=json

**Comment by ChristophEwertowski** [comment]
If it's a data level issue we might get a problem with the display of the authors / institutions. Right now all "authors" are displayed in one line in the set contribution order ([example](http://alpha.lobid.org/resources/HT013480902)). If there is an institution together with a person, how do we call the field in the frontend? *Beteiligte*, *Mitwirkende*?

**Comment by fsteeg** [comment]
The contributions are already grouped by role, see: http://lobid.org/resources/HT018776640

When the role label for `CorporateBody` is fixed in the data, that new label will automatically be used.

For some details see also:  http://blog.lobid.org/2016/12/13/data-modeling-client-effects.html

**Comment by ChristophEwertowski** [comment]
Changed the standard for corporateBodies with MAB `2?[02468][-a][-12].9` to issuing body which has the label `Herausgeber/in`. See [HT003654516 (production)](http://lobid.org/resources/HT003654516) / [HT003654516 (test)](http://test.lobid.org/resources/HT003654516).

**Comment by acka47** [comment]
"Autor/in" definitely isn't a good choice for coporate bodies from `200` but it might be the best we have. In RAK corporate bodies from `200.a` are called "Urheber" in RDA "creator" (German: "Geistiger Schöpfer"). Thus, I think that using the MARC relator http://id.loc.gov/vocabulary/relators/cre ("creator") is actually correct.

Unfortunately, there exists no handy label like "creator" in German that both fits with persons and corporate bodies. An attempt to establish the use of "Kreator" in the German language probably won't be succesful. Using "Geistiger Schöpfer" doesn't sound like a good solution.  

This discussion already popped up in 2015 in the context of NWBib, see https://github.com/hbz/nwbib/issues/164. There, I wrote in a [comment](https://github.com/hbz/nwbib/issues/164#issuecomment-195402223):

> We will get a clear differentiation between corporate bodies as creators and persons as creators with API 2.0. The issue will be solved then.

Obviously, we just can not use the same label for role "creator. There are three possible solutions:

1. Stick to the current approach using one label like"Autor/in" or another one for both persons and corporate bodies. (BTW, we are using "Autor/in" in NWBib for years now without anyone ever having complained.)
2. Assign different labels for role "creator" in the JSON, depending on whether we are dealing with a person or a corporate body. I don't know how feasible this is with the current labels.json approach.
3. Override the use of the label provided by the data in the frontend for the case we have corporate bodies as creators. 

For now, I am in favour of 1.) and to close this issue. We can reopen it whenever people start complaining.

**Comment by ChristophEwertowski** [comment]
In my opinion the best option is to stay with "Autor/in" until a demand arises. Closing this issue.
