### ISSUE TITLE
Move lobid-resources and lobid-resources-web into a single repo

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources-web#38]
With the issue assignment for lobid-resources and lobid-resources-web getting messy, I think we should evaluate ways to move these two repos into a single repo.

Cleanest way would be to actually unify the software, including the build system, and updates via HTTP, like in lobid-organisations. I discussed this with @dr0i before and it might not make sense here.

But even without that, I think a single repo makes sense. We could have top-level `data` and `web` (or such) folders containing the current repos, with their builds. We'd get a single place to open issues, document the service, etc.

**Comment by acka47** [comment]
Sounds l&#477;dd&#7433;uu&#477;s&#477;&#7433;&#633;.

**Comment by dr0i** [comment]
... also the `context.json` would be shared more overtly.

**Comment by dr0i** [comment]
Should be deployed on quaoar1 as such. Config monit too.

**Comment by fsteeg** [comment]
Set up deployment and monitoring on quaoar:

`sudo pico /etc/monit/conf.d/play-instances.rc`

```
check process lobid-resources with pidfile "/home/sol/git/lobid-resources/web/target/universal/stage/RUNNING_PID"
        start program = "/home/sol/git/lobid-resources/web/monit_restart.sh lobid-resources/web start 7500"
                as uid sol and gid sol
        stop program = "/home/sol/git/lobid-resources/web/monit_restart.sh lobid-resources/web stop 7500"
                as uid sol and gid sol
        if failed host 127.0.0.1 port 7500 then start
        if 5 restarts within 5 cycles then timeout

check process lobid-resources-staging with pidfile "/home/sol/git/lobid-resources-staging/web/target/universal/stage/RUNNING_PID"
        start program = "/home/sol/git/lobid-resources-staging/web/monit_restart.sh lobid-resources-staging/web start 7501"
                as uid sol and gid sol
        stop program = "/home/sol/git/lobid-resources-staging/web/monit_restart.sh lobid-resources-web stop 7501"
                as uid sol and gid sol
        if failed host 127.0.0.1 port 7501 then start
        if 5 restarts within 5 cycles then timeout
```

`sudo monit reload`

`sudo monit status` looks good.

**Comment by dr0i** [comment]
+1
