### ISSUE TITLE
Switch test, beta, and empty subdomains to this web app

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources-web#6]
Depends on #5 to serve current content of test, beta, and empty subdomains.

**Comment by fsteeg** [comment]
This is now `ready`, since JSON support is deployed to alpha, see https://github.com/hbz/lobid-resources-web/pull/11, #5 

@jschnasse: will we need to coordinate this with you? Are you currently using `http://beta.lobid.org/resources` or `http://lobid.org/resources` (i.e. API 2.0) responses as JSON, but without requesting JSON via header? In that case, the switch would cause you to get HTML instead of JSON.

We will also have to update the URL pattern in the NWBib config.

**Comment by fsteeg** [comment]
@jschnasse As a quick follow up on our lunch discussion today: what I mentioned is actually true, if no `Accept` header is given, you'll still get JSON: `curl http://alpha.lobid.org/resources/HT019116616`

**Comment by dr0i** [comment]
What's the status of this? Shall we do the switch?

**Comment by fsteeg** [comment]
+1 from me.

We should wait for +1s by @acka47 and @jschnasse.

**Comment by acka47** [comment]
+1

**Comment by jschnasse** [comment]
+1

**Comment by fsteeg** [comment]
I've set up the proxies on emphytos, and disabled the previous redirects (except for ZDB).

See:

http://beta.lobid.org/resources
http://beta.lobid.org/resources/search?q=glessen
http://beta.lobid.org/resources/TT001181932
http://beta.lobid.org/items/TT001181932:DE-107:11.8631

http://lobid.org/resources
http://lobid.org/resources/search?q=glessen
http://lobid.org/resources/TT001181932
http://lobid.org/items/TT001181932:DE-107:11.8631

`curl http://lobid.org/resources/TT001181932`

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Comment by dr0i** [comment]
@fsteeg we have a git repo for the configs. Commit and push the changes: +1 from me too.

**Comment by fsteeg** [comment]
Right, completely forgot about that repo. Will set up the new project structure (see https://github.com/hbz/lobid-resources-web/issues/38#issuecomment-276412684), and a staging system, and open a pull request against https://github.com/hbz/lobid-webserver.
